CLIENT_TYPE_REQ_OK = '0'
CLIENT_TYPE_CLOSE = '-0'
CLIENT_TYPE_REGISTER = '-2'
CLIENT_TYPE_NONE = '-1'

CLIENT_TYPE_API = '2'
CLIENT_TYPE_RASPBERRY = '3'
CLIENT_TYPE_DEVICE = '4'

STATUS_OK = 'OK'
STATUS_NO = 'NO'

SERVER_URL = '127.0.0.1'
SERVER_PORT = 7770
